version: 2
registries:
  nuget-feed-nuget-pkg-github-com-ashleighadams-index-json:
    type: nuget-feed
    url: https://nuget.pkg.github.com/AshleighAdams/index.json
    username: "${{secrets.NUGET_FEED_NUGET_PKG_GITHUB_COM_ASHLEIGHADAMS_INDEX_JSON_USERNAME}}"
    password: "${{secrets.NUGET_FEED_NUGET_PKG_GITHUB_COM_ASHLEIGHADAMS_INDEX_JSON_PASSWORD}}"
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  registries:
  - nuget-feed-nuget-pkg-github-com-ashleighadams-index-json
