# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: |
        Swis.Runtime/Swis.Runtime.csproj
        Swis.Development/Swis.Development.csproj
        UnitTests/UnitTests.csproj
      feedsToUse: 'select'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: |
        Swis.Runtime/Swis.Runtime.csproj
        Swis.Development/Swis.Development.csproj
        UnitTests/UnitTests.csproj
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'UnitTests/UnitTests.csproj'
      arguments: '--collect "Code coverage"'
      testRunTitle: 'Test'